package com.amotassic.dabaosword.util;

import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.sound.SoundEvent;
import net.minecraft.util.Identifier;

public class Sounds {
    public static final SoundEvent NAHIDA1 = register("nahida1");
    public static final SoundEvent NAHIDA2 = register("nahida2");
    public static final SoundEvent NAHIDA3 = register("nahida3");
    public static final SoundEvent FALL1 = register("falling_attack1");
    public static final SoundEvent FALL2 = register("falling_attack2");
    public static final SoundEvent TIEJI1 = register("tieji1");
    public static final SoundEvent TIEJI2 = register("tieji2");
    public static final SoundEvent GANGLIE1 = register("ganglie1");
    public static final SoundEvent GANGLIE2 = register("ganglie2");
    public static final SoundEvent FANGZHU1 = register("fangzhu1");
    public static final SoundEvent FANGZHU2 = register("fangzhu2");
    public static final SoundEvent XINGSHANG1 = register("xingshang1");
    public static final SoundEvent XINGSHANG2 = register("xingshang2");
    public static final SoundEvent CHENGLVE1 = register("chenglve1");
    public static final SoundEvent CHENGLVE2 = register("chenglve2");
    public static final SoundEvent CUNMU1 = register("cunmu1");
    public static final SoundEvent CUNMU2 = register("cunmu2");
    public static final SoundEvent SHICAI1 = register("shicai1");
    public static final SoundEvent SHICAI2 = register("shicai2");
    public static final SoundEvent XUYOU = register("xuyou");
    public static final SoundEvent DUANLIANG1 = register("duanliang1");
    public static final SoundEvent DUANLIANG2 = register("duanliang2");
    public static final SoundEvent LUOSHEN1 = register("luoshen1");
    public static final SoundEvent LUOSHEN2 = register("luoshen2");
    public static final SoundEvent QIXI1 = register("qixi1");
    public static final SoundEvent QIXI2 = register("qixi2");
    public static final SoundEvent QINGGUO1 = register("qingguo1");
    public static final SoundEvent QINGGUO2 = register("qingguo2");
    public static final SoundEvent LIEGONG1 = register("liegong1");
    public static final SoundEvent LIEGONG2 = register("liegong2");
    public static final SoundEvent GONGAO1 = register("gongao1");
    public static final SoundEvent GONGAO2 = register("gongao2");
    public static final SoundEvent WEIZHONG = register("weizhong");
    public static final SoundEvent BENXI1 = register("benxi1");
    public static final SoundEvent BENXI2 = register("benxi2");
    public static final SoundEvent LEIJI1 = register("leiji1");
    public static final SoundEvent LEIJI2 = register("leiji2");
    public static final SoundEvent GIFTBOX = register("giftbox");
    public static final SoundEvent KANPO1 = register("kanpo1");
    public static final SoundEvent KANPO2 = register("kanpo2");
    public static final SoundEvent GUOSE1 = register("guose1");
    public static final SoundEvent GUOSE2 = register("guose2");
    public static final SoundEvent LIULI1 = register("liuli1");
    public static final SoundEvent LIULI2 = register("liuli2");
    public static final SoundEvent JUEQING1 = register("jueqing1");
    public static final SoundEvent JUEQING2 = register("jueqing2");
    public static final SoundEvent LUANJI1 = register("luanji1");
    public static final SoundEvent LUANJI2 = register("luanji2");
    public static final SoundEvent LUANJI3 = register("luanji3");
    public static final SoundEvent LUANJI4 = register("luanji4");
    public static final SoundEvent KUROU1 = register("kurou1");
    public static final SoundEvent KUROU2 = register("kurou2");
    public static final SoundEvent JIZHI1 = register("jizhi1");
    public static final SoundEvent JIZHI2 = register("jizhi2");
    public static final SoundEvent QICE1 = register("qice1");
    public static final SoundEvent QICE2 = register("qice2");
    public static final SoundEvent LUOYI1 = register("luoyi1");
    public static final SoundEvent LUOYI2 = register("luoyi2");
    public static final SoundEvent HUOJI1 = register("huoji1");
    public static final SoundEvent HUOJI2 = register("huoji2");
    public static final SoundEvent QUANJI1 = register("quanji1");
    public static final SoundEvent QUANJI2 = register("quanji2");
    public static final SoundEvent ZILI1 = register("zili1");
    public static final SoundEvent ZILI2 = register("zili2");
    public static final SoundEvent PAIYI1 = register("paiyi1");
    public static final SoundEvent PAIYI2 = register("paiyi2");
    public static final SoundEvent PAIYI3 = register("paiyi3");
    public static final SoundEvent PAIYI4 = register("paiyi4");
    public static final SoundEvent YIJI1 = register("yiji1");
    public static final SoundEvent YIJI2 = register("yiji2");
    public static final SoundEvent TAOLUAN1 = register("taoluan1");
    public static final SoundEvent TAOLUAN2 = register("taoluan2");
    public static final SoundEvent POJUN1 = register("pojun1");
    public static final SoundEvent POJUN2 = register("pojun2");
    public static final SoundEvent KUANGGU1 = register("kuanggu1");
    public static final SoundEvent KUANGGU2 = register("kuanggu2");


    public static final SoundEvent BINGLIANG = register("bingliang");
    public static final SoundEvent GUOHE = register("guohe");
    public static final SoundEvent HUOGONG = register("huogong");
    public static final SoundEvent JIEDAO = register("jiedao");
    public static final SoundEvent JIU = register("jiu");
    public static final SoundEvent JUEDOU = register("juedou");
    public static final SoundEvent LEBU = register("lebu");
    public static final SoundEvent RECOVER = register("recover");
    public static final SoundEvent SHAN = register("shan");
    public static final SoundEvent SHUNSHOU = register("shunshou");
    public static final SoundEvent TAOYUAN = register("taoyuan");
    public static final SoundEvent TIESUO = register("tiesuo");
    public static final SoundEvent WANJIAN = register("wanjian");
    public static final SoundEvent WUXIE = register("wuxie");
    public static final SoundEvent WUZHONG = register("wuzhong");
    public static final SoundEvent NANMAN = register("nanman");
    public static final SoundEvent SHA = register("sha");
    public static final SoundEvent SHA_FIRE = register("sha_fire");
    public static final SoundEvent SHA_THUNDER = register("sha_thunder");

    public static void sound() {}
    public static SoundEvent register(String name){
        Identifier identifier = Identifier.of("dabaosword",name);
        return Registry.register(Registries.SOUND_EVENT,identifier,SoundEvent.of(identifier));
    }
}
